# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM amazoncorretto:8-alpine-jdk
MAINTAINER emaaristimuno
COPY target/sertec-0.0.1-SNAPSHOT.jar sertec-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/sertec-0.0.1-SNAPSHOT.jar"]


